### ISSUE TITLE
Create a storage share header encode bug

### ISSUE THREAD

**Issue by yupwei68** [tombuildsstuff/giovanni#20]
code : https://github.com/tombuildsstuff/giovanni/blob/0afd1f7da4b615b508fde90738c73d9dca1ad741/storage/2018-11-09/file/shares/create.go#L76

Ref to :https://github.com/terraform-providers/terraform-provider-azurerm/issues/4782 

While creating a storage share: the header value for "x-ms-share-quota"  encounters an UTF-8 encoding bug. 
Error: Error creating Share "bits" (Account "nancyctest1234" / Resource Group "nancyc-rg-1"): shares.Client#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: error response cannot be parsed: "\ufeff<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format.\nRequestId:ad94872b-101a-00c5-1ec1-9230c3000000\nTime:2019-11-04T03:36:16.4360584Z</Message><HeaderName>x-ms-share-quota</HeaderName><HeaderValue>50</HeaderValue></Error>" error: invalid character 'ï' looking for beginning of value

**Comment by tombuildsstuff** [comment]
hi @yupwei68 

Thanks for opening this issue.

This UTF8-parsing error is coming from a bug in Azure/Go-AutoRest (where errors were parsed as Json always, rather than as XML if XML is in the response) which has since been fixed and has shipped in version 0.6.0 of this library - which will ship in v1.37 of the Terraform Provider for Azure.

As such I'm going to close this issue for the moment - but the error message should become clearer in v1.37 of Terraform's Azure Provider. It's likely this is to do with the minimum quota size changing depending on the Storage Account Type being used (e.g. Standard vs Premium) - as is detailed in https://github.com/terraform-providers/terraform-provider-azurerm/issues/4782

Thanks!
